version: '3'

services:
  nginx:
    build: .
    ports:
      - '8443:443'
  keycloak:
    image: 'jboss/keycloak'
    environment:
      - KEYCLOAK_PASSWORD=pass
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=MYSQL
      - DB_ADDR=mysql
      - DB_DATABASE=keycloak
      - DB_USER=raees
      - DB_PASSWORD=admin123
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: raees
      MYSQL_PASSWORD: admin123

volumes:
  mysql_data:
    driver: local
